---
releases:
  - name:    blacksmith
    version: 2.0.0
    sha1:    sha256:37e7aec351ea56ec326076e14712652cd9ae9ad98ac96fe317a73332efe3a762
    url:     https://github.com/blacksmith-community/blacksmith-boshrelease/releases/download/v2.0.0/blacksmith-2.0.0.tgz

  - name:    bosh
    version: "282.0.7"
    sha1:    sha256:9287abbd9d5bad40d26b9b6a4a611c18bc17768ee3090d54192f70e69b0e42db
    url:     (( concat "https://bosh.io/d/github.com/cloudfoundry/bosh?v=" releases.bosh.version ))

  - name:    "bpm"
    version: "1.4.20"
    sha1:    sha256:1984129b352cd414e29a7dcffcf076049a776afa511cd44b587065f6e618cc6d
    url:     (( concat "https://bosh.io/d/github.com/cloudfoundry/bpm-release?v=" releases.bpm.version ))

  - name:    routing
    version: "0.343.0"
    sha1:    sha256:1409f3a0e56d89683f50c2d6c0fcb38d1a297c3710b3c067fb75182e7a7df356
    url:     (( concat "https://bosh.io/d/github.com/cloudfoundry/routing-release?v=" releases.routing.version ))

  - name:    bosh-dns-aliases
    version: "0.0.4"
    sha1:    sha256:27ef8965dc4f1633479613743e782566e3b7fba5d28dad3d50488c2919eac0da
    url:     (( concat "https://bosh.io/d/github.com/cloudfoundry/bosh-dns-aliases-release?v=" releases.bosh-dns-aliases.version ))
