---
meta:
  default:
    postgresql_tags:
      - blacksmith
      - dedicated
      - postgresql

    postgresql_plans:
      standalone:
        name: standalone
        description: A dedicated PostgreSQL server, with no redundancy or replication
        limit: 7
        type: standalone
        vm_type: default
      cluster:
        name: cluster
        description: A 3-node PostgreSQL replicated cluster, with PGPoolII front-end
        limit: 4
        type: cluster
        vm_type: default

releases:
  - name:    postgresql-forge
    version: 0.1.1
    url:     https://github.com/blacksmith-community/postgresql-forge-boshrelease/releases/download/v0.1.1/postgresql-forge-0.1.1.tgz
    sha1:    2885d5d7e8bf7ad8321d1ea0eebfd6e01d60f4fc

params:
  releases:
    - (( append ))
    - name:    postgres
      version: 2.0.0
      url:     https://github.com/cloudfoundry-community/postgres-boshrelease/releases/download/v2.0.0/postgres-2.0.0.tgz
      sha1:    dea5cad517c62afaf97a1b31df41ad691928d960

instance_groups:
  - name: blacksmith
    jobs:
      - release: postgresql-forge
        name:    postgresql-blacksmith-plans
        properties:
          plans: (( grab params.postgresql_plans || meta.default.postgresql_plans ))
          service:
            id:          (( grab params.postgresql_service_id          || "postgresql" ))
            name:        (( grab params.postgresql_service_name        || params.postgresql_service_id || "postgresql" ))
            description: (( grab params.postgresql_service_description || "A dedicated PostgreSQL instance, deployed on-demand" ))
            tags:        (( grab params.postgresql_service_tags        || meta.default.postgresql_tags ))
            limit:       (( grab params.postgresql_service_limit       || 0 ))
