---
meta:
  environment: (( grab genesis.env || params.env ))
  bosh_env: (( grab genesis.bosh_env || params.bosh_env || params.env ))

  default:
    valkey_tags:
    - blacksmith
    - dedicated
    - valkey
    - redis

    valkey_plans:
      standalone:
        name: standalone
        description: A dedicated Valkey server, with no redundancy or replication
        limit: 7
        type: standalone
        version: 8
        vm_type: default
      cluster:
        name: cluster
        description: A Valkey cluster with 3 master nodes and 3 replica nodes
        limit: 5
        type: cluster
        version: 8
        vm_type: default
        masters: 3
        replicas: 1

releases:
 - name: valkey-forge
   version: 1.0.1
   url: https://github.com/blacksmith-community/valkey-forge-boshrelease/releases/download/v1.0.1/valkey-forge-1.0.1.tar.gz
   sha1: sha256:f501b918934ad7e16daaa47d5b30415162dcdfa1b3b23474faa4b8d4718f898c

params:
  releases:
  - (( append ))
  - (( grab releases.valkey-forge ))

instance_groups:
- name: blacksmith
  jobs:
  - release: valkey-forge
    name:    valkey-blacksmith-plans
    properties:
      environment: (( grab meta.environment ))
      bosh_env: (( grab meta.bosh_env ))

      plans: (( grab params.valkey_plans || meta.default.valkey_plans ))
      service:
        id:          (( grab params.valkey_service_id          || "valkey" ))
        name:        (( grab params.valkey_service_name        || params.valkey_service_id || "valkey" ))
        description: (( grab params.valkey_service_description || "A dedicated Valkey instance, deployed on-demand" ))
        tags:        (( grab params.valkey_service_tags        || meta.default.valkey_tags ))
        limit:       (( grab params.valkey_service_limit       || 0 ))
        type:        (( grab params.valkey_service_type        || "standalone" ))
