---
instance_groups:
  - name: blacksmith
    jobs:
      - { release: bosh, name: nats }
      - { release: bosh, name: postgres-9.4 }
      - { release: bosh, name: blobstore }
      - { release: bosh, name: director }
      - { release: bosh, name: health_monitor }

    properties:
      ## ENVIRONMENT
      env:
        http_proxy:  (( grab params.http_proxy  || "" ))
        https_proxy: (( grab params.https_proxy || "" ))
        no_proxy:    (( grab params.no_proxy    || "" ))

      ## NATS CONFIGURATION
      nats:
        address: (( grab params.ip ))
        user: nats
        password: (( vault meta.vault "/nats:password" ))
        tls:
          ca: (( vault meta.vault "/tls/nats/ca:certificate" ))
          client_ca:
            certificate: (( vault meta.vault "/tls/nats/ca:certificate" ))
            private_key: (( vault meta.vault "/tls/nats/ca:key"         ))
          server:
            certificate: (( vault meta.vault "/tls/nats/server:certificate" ))
            private_key: (( vault meta.vault "/tls/nats/server:key"         ))
          director:
            certificate: (( vault meta.vault "/tls/nats/director:certificate" ))
            private_key: (( vault meta.vault "/tls/nats/director:key"         ))
          health_monitor:
            certificate: (( vault meta.vault "/tls/nats/hm:certificate" ))
            private_key: (( vault meta.vault "/tls/nats/hm:key"         ))

      ## BLOBSTORE CONFIGURATION
      blobstore:
        address: (( grab params.ip ))
        port: 25250
        provider: dav
        director:
          user:     director
          password: (( vault meta.vault "/blobstore/director:password" ))
        agent:
          user:     agent
          password: (( vault meta.vault "/blobstore/agent:password" ))

      ## POSTGRES CONFIGURATION
      postgres: &db
        listen_address: 127.0.0.1
        host: 127.0.0.1
        user: postgres
        password: (( vault meta.vault "/db:password" ))
        database: bosh
        adapter: postgres

      ## BOSH DIRECTOR CONFIGURATION
      director:
        name: (( concat params.env "-blacksmith" ))
        address: (( grab params.ip ))
        db: *db
        flush_arp: true
        enable_post_deploy: true
        generate_vm_passwords: true
        enable_dedicated_status_worker: true
        enable_nats_delivered_templates: true
        workers: 4
        local_dns:
          enabled: true
        events:
          record_events: true
        ssl:
          cert: (( vault meta.vault "/tls/director:certificate" ))
          key:  (( vault meta.vault "/tls/director:key" ))
        user_management:
          provider: local
          local:
            users:
            - name:     admin
              password: (( vault meta.vault "/users/admin:password" ))

            - name:     hm
              password: (( vault meta.vault "/users/hm:password" ))

            - name:     blacksmith
              password: (( vault meta.vault "/users/blacksmith:password" ))

      ## HEALTH MONITOR CONFIGURATION
      hm:
        resurrector_enabled: true
        director_account:
          user: hm
          password: (( vault meta.vault "/users/hm:password" ))
          ca_cert:  (( vault meta.vault "/tls/ca:certificate" ))

releases:
  - name:    bosh
    version: "264.5.0"
    url:     https://s3.amazonaws.com/bosh-compiled-release-tarballs/bosh-264.5.0-ubuntu-trusty-3468.13-20171214-231004-994547171-20171214231009.tgz?versionId=66MJhlOuDZn3SM18oBXxVP6DuV2BOXZi
    sha1:    0ff5b856bbdb901691e98283823fd1f112768569
