---
meta:
  bosh:
    exodus: (( concat $GENESIS_EXODUS_MOUNT genesis.env "/bosh" ))
  external_bosh_username: (( vault meta.bosh.exodus ":blacksmith_user" ))
  external_bosh_password: (( vault meta.bosh.exodus ":blacksmith_password" ))
  external_bosh_address: (( vault meta.bosh.exodus ":url" ))
  external_bosh_cacert: (( vault meta.bosh.exodus ":ca_cert" ))

exodus:
  bosh_cacert: (( grab params.external_bosh.cacert || meta.external_bosh_cacert ))

params:
  cloud_config: []

instance_groups:
  - name: blacksmith
    jobs:
      - release: blacksmith
        name: blacksmith
        properties:
          bosh:
            username: (( grab params.external_bosh.username || meta.external_bosh_username ))
            password: (( grab params.external_bosh.password || meta.external_bosh_password ))
            address:  (( grab params.external_bosh.address || meta.external_bosh_address))
            stemcells: []
            releases: []
            cloud-config: []
