---
# TODO: Add colocated shield agent + configuration here
meta:
  shield:
    default_exodus: (( concat $GENESIS_EXODUS_MOUNT params.shield.deployment_env "/" params.shield.deployment_type ":" ))

params:
  shield_exodus_path: (( grab meta.shield.default_exodus ))

instance_groups:
  - name: blacksmith
    jobs:
      - name:    shield-agent
        release: shield
        properties:
          shield: 
            shield-url: (( vault params.shield_exodus_path "url" )) 
            require-shield-core: false
            core:
              ca: (( vault params.shield_exodus_path "ca" ))
            agent:
              key: (( vault params.shield_exodus_path "key" ))
            env:
              http_proxy: ""
              https_proxy: ""
              no_proxy: ""