#!/bin/bash
set -eu

declare -a merge

# TODO: Refactor instead of using validate_features to use loops enabling ops/ dir.

#validate_features aws azure google openstack vsphere external-bosh \
#                  redis redis-tls redis-dual-mode \
#                  rabbitmq rabbitmq-tls rabbitmq-dual-mode rabbitmq-dashboard-registration \
#                  postgresql mariadb kubernetes broker-tls

# We always start out with the skeleton of a BOSH deployment,
# and add-in a local UAA and a Credhub
merge=( manifests/blacksmith/blacksmith.yml )

iaas=0
if want_feature "external-bosh"; then
  merge+=( manifests/blacksmith/external-bosh.yml )
  # No IaaS Specification needed with external bosh
  iaas=$(( iaas + 1 ))
else
  merge+=( manifests/blacksmith/bosh.yml )
fi

if want_feature "broker-tls"; then
  merge+=( manifests/blacksmith/broker-tls.yml )
fi

if want_feature "shield-backups"; then
  merge+=( manifests/blacksmith/shield-backups.yml )
fi

for want in ${GENESIS_REQUESTED_FEATURES}
do
  case "$want" in
    # IaaS selector feature flags
    (aws|azure|google|openstack|vsphere)
      iaas=$(( iaas + 1 ))
      merge+=( manifests/iaas/$want.yml )
      case $want in
        (vsphere) ;; # vSphere doesn't need a registry
        (*)          # but everyone else does...
          merge+=( manifests/addons/registry.yml )
          ;;
      esac
      ;;
  esac
done

forges=0
for want in ${GENESIS_REQUESTED_FEATURES}; do
  case "$want" in
  # Forges
  (rabbitmq|redis|postgresql|mariadb|kubernetes)
    forges=$(( forges + 1 ))
    merge+=( manifests/forges/$want.yml )
    ;;
  (*)
    if [[ -f "$GENESIS_ROOT/ops/$want.yml" ]] ; then
      merge+=( "$GENESIS_ROOT/ops/$want.yml" )
    fi
    ;;
  esac
done

if want_feature "redis-tls"; then
  merge+=( manifests/forges/redis-tls.yml )
fi

if want_feature "redis-dual-mode"; then
  merge+=( manifests/forges/redis-dual-mode.yml )
fi

if want_feature "rabbitmq-tls"; then
  merge+=( manifests/forges/rabbitmq-tls.yml )
fi

if want_feature "rabbitmq-dual-mode"; then
  merge+=( manifests/forges/rabbitmq-dual-mode.yml )
fi

if want_feature "rabbitmq-dashboard-registration"; then
  merge+=( manifests/forges/rabbitmq-dashboard-registration.yml )
fi

# Sanity Check Time!
# If we haven't chosen an IaaS, that's a problem.
if [[ $iaas == 0 ]]; then
  echo >&2 "You have not enabled an IaaS feature flag."
  exit 1
fi
# If we have chosen more than one IaaS, that's a problem.
if [[ $iaas > 1 ]]; then
  echo >&2 "You have enabled more than one IaaS feature flag."
  exit 1
fi
# If we didn't activate at least one Forge, that's a problem.
if [[ $forges == 0 ]]; then
  echo >&2 "You have not activated any Blacksmith Forges."
  exit 1
fi

echo "${merge[@]}"
