#!/bin/bash

# Cloud Config checks
if [[ -n "$GENESIS_CLOUD_CONFIG" ]] ; then
  if ! want_feature proto; then
    cloud_config_needs vm_type    $(lookup --partial params.vm_type blacksmith)
    cloud_config_needs network    $(lookup --partial params.network blacksmith)
    check_cloud_config && describe "  cloud-config [#G{OK}]"
  fi
fi

# Environment Parameter checks
ok=yes
if want_feature vsphere; then
  for e in ephemeral persistent; do
    t=$(typeof params.vsphere_${e}_datastores)
    if [[ $t != "list" ]]; then
      describe "  ${e} vsphere datastores is a #Y{$t}, not a list [#R{FAILED}]"
      ok=no
    else
      describe "  ${e} vsphere datastores checks out [#G{OK}]"
    fi
  done
fi

ip=$(lookup --partial params.ip)
describe "  checking if our certificates match the director static ip ($ip)..."
vault="$GENESIS_SECRETS_MOUNT/$GENESIS_VAULT_PREFIX"
for cert in tls/director \
            tls/nats/server; do
  if ! safe exists "$vault/$cert"; then
    describe "    - $vault/$cert [#Y{MISSING}]"
  else
    if safe --quiet x509 validate "$vault/$cert" --for "$ip" >/dev/null 2>&1; then
      describe "    - $vault/$cert [#G{OK}]"
    else
      describe "    - $vault/$cert [#R{INVALID}]"
      safe x509 validate "$vault/$cert" --for "$ip" 2>&1 | sed -e 's/^/      /';
      ok=no
      echo
    fi
  fi
done

if [[ "$ok" = "yes" ]]; then
  describe "  environment files [#G{OK}]"
else
  describe "  environment files [#R{FAILED}]"
  exit 1
fi

