#!/bin/bash
set -eu
vault="secret/$GENESIS_VAULT_PREFIX"

ip=$(lookup params.ip)
port=$(lookup params.port 3000)
export BLACKSMITH_URL=http://$ip:$port
export BLACKSMITH_USERNAME=blacksmith
export BLACKSMITH_PASSWORD=$(safe read $vault/broker:password)

export BOSH_ENVIRONMENT=https://$(lookup params.ip):25555
export BOSH_CA_CERT=$(safe read $vault/tls/ca:certificate)
export BOSH_CLIENT=admin
export BOSH_CLIENT_SECRET=$(safe read $vault/users/admin:password)


describe "ca certificate"
         safe read $vault/tls/ca:certificate
    echo
    echo "bosh env"
         bosh env --tty | sed -e 's/^/  /';
    echo
    echo
    echo "blacksmith (internal) bosh director"
describe "  bosh url: #C{$BOSH_ENVIRONMENT}"
describe "  username: #M{$BOSH_CLIENT}"
describe "  password: #G{$BOSH_CLIENT_SECRET}"
    echo
    echo
    echo "blacksmith web management UI"
describe "  web url:   #C{$BLACKSMITH_URL}"
describe "  username:  #M{$BLACKSMITH_USERNAME}"
describe "  password:  #G{$BLACKSMITH_PASSWORD}"
describe "  clickable: #B{http://$BLACKSMITH_USERNAME:$BLACKSMITH_PASSWORD@$ip:$port}"
    echo
    echo
    echo "blacksmith catalog"
if ! command -v boss >/dev/null 2>&1; then
    echo "  !!! install the 'boss' cli to query the blacksmith catalog"
    echo "      (https://github.com/jhunt/boss)"
else
         boss catalog | sed -e 's/^/  /';
fi
