#!/bin/bash
set -eu

if [[ $GENESIS_DEPLOY_RC == 0 ]]
then
  describe \
    "" \
    "#M{$GENESIS_ENVIRONMENT} Blacksmith Broker deployed!" \
    "" \
    "For details about the deployment, run" \
    "" \
    "  #G{genesis info $GENESIS_ENVIRONMENT}" \
    "" \
    "To access the Blacksmith Web Management Console, run" \
    "" \
    "  #G{genesis do $GENESIS_ENVIRONMENT -- visit}" \
    "" \
    "To log into the Blacksmith BOSH director," \
    "(to troubleshoot service provisioning), run" \
    "" \
    "  #G{genesis do $GENESIS_ENVIRONMENT -- bosh}" \
    ""
fi

exit 0
