#!/bin/bash
set -eu

if [[ $GENESIS_DEPLOY_RC == 0 ]]; then

      echo; echo;
  describe "#M{$GENESIS_ENVIRONMENT} Blacksmith Broker deployed!"
      echo
      echo "For details about the deployment, run"
      echo
  describe "  #G{genesis info $GENESIS_ENVIRONMENT}"
      echo
      echo "To access the Blacksmith Web Management Console, run"
      echo
  describe "  #G{genesis do $GENESIS_ENVIRONMENT visit}"
      echo
      echo "To log into the Blacksmith BOSH director,"
      echo "(to troubleshoot service provisioning), run"
      echo
  describe "  #G{genesis do $GENESIS_ENVIRONMENT bosh}"
      echo

fi
