#!/bin/bash

cpis=0
forges=0

read -r -d '' CPI_USAGE <<EOF
  BOSH Director Cloud Provider Interfaces
  (you need *exactly one* of these)

     vsphere  - VMWare's vSphere ESXi+vCenter
EOF
read -r -d '' FORGE_USAGE <<EOF
  Blacksmith Forges
  (you need *at least one* of these)

     redis      - Redis Key-Value storage, available
                  as dedicated, single-instance VMs.

     rabbitmq   - RabbitMQ messaging queue, available
                  as standalone VMs and clustered.

     postgresql - PotgreSQL database server, available
                  as standalone VMs and clustered with
                  replication.
EOF

for kit in $@; do
  case $kit in

   ######  ########  ####
  ##    ## ##     ##  ##
  ##       ##     ##  ##
  ##       ########   ##
  ##       ##         ##
  ##    ## ##         ##
   ######  ##        ####
  vsphere)
    cpis=$(( cpis + 1 ))
    ;;


  ########  #######  ########   ######   ########  ######
  ##       ##     ## ##     ## ##    ##  ##       ##    ##
  ##       ##     ## ##     ## ##        ##       ##
  ######   ##     ## ########  ##   #### ######    ######
  ##       ##     ## ##   ##   ##    ##  ##             ##
  ##       ##     ## ##    ##  ##    ##  ##       ##    ##
  ##        #######  ##     ##  ######   ########  ######
  redis)
    forges=$(( forges + 1 ))
    ;;
  rabbitmq)
    forges=$(( forges + 1 ))
    ;;
  postgresql)
    forges=$(( forges + 1 ))
    ;;

  *)
    cat >&2 <<EOF
Unrecognized subkit '$kit'
This Genesis kit knows about the following subkits:

$CPI_USAGE


$FORGE_USAGE

EOF
    exit 1
  esac
done

if [[ $cpis -ne 1 ]]; then
  cat >&2 <<EOF
You have not specified a BOSH Director Cloud Provider Interface
subkit.  Blacksmith needs to know how to talk to the IaaS layer
you wish to use to deploy on-demand services.

$CPI_USAGE

EOF
  exit 1
fi

if [[ $forges -lt 1 ]]; then
  cat >&2 <<EOF
You have not specified any Blacksmith Forges to use.
Each Forge provides the necessary bits to deploy an entire class
of on-demand service, i.e. PostgreSQL database servers.

$FORGE_USAGE

EOF
  exit 1
fi


echo "$@"
