---
meta:
  ocfp:
    env:
      scale: (( grab params.env.scale || "dev" ))

    vault:
      tf: (( concat genesis.secrets_mount "tf/" genesis.vault_env ))

    certs:
      trusted:
        - (( vault genesis.secrets_mount "certs/org:ca" )) # Organization CA, if exists
        - (( vault genesis.secrets_mount "certs/dbs:ca" )) # External Databases CA

  stemcell:
    name:    (( grab params.stemcell_name    || "bionic" ))
    os:      (( grab params.stemcell_os      || "ubuntu-bionic" ))
    version: (( grab params.stemcell_version || "latest" ))

  blacksmith:
    cloud_config: {} # TODO: OCFP Reference Arch based Cloud Config

    domain: (( vault meta.ocfp.vault.tf "/net/blacksmith:fqdn" ))
    ip:     (( vault meta.ocfp.vault.tf "/net/blacksmith:ip" ))
    az:     (( vault meta.ocfp.vault.tf "/bosh/iaas/subnets/ocfp/0:availability_zone" ))

    disk_type: (( concat "blacksmith-" meta.ocfp.env.scale ))
    vm_type:   (( concat "blacksmith-" meta.ocfp.env.scale ))
    network:   (( concat genesis.env "-ocf" ))

    debug:      false
    shareable:  false

    broker:
      # NOTE: TLS is always enabled as broker-tls is included by default.
      url: (( "https://" meta.blacksmith.domain ))

      username: blacksmith
      password: (( vault meta.vault "/broker:password" ))
