---
meta:
  ocfp:
    env:
      scale: (( grab params.env.scale || "dev" ))

    vault:
      tf: (( concat genesis.secrets_mount "tf/" genesis.vault_env ))

    certs:
      trusted:
        - (( vault genesis.secrets_mount "certs/org:ca" )) # Organization CA, if exists
        - (( vault genesis.secrets_mount "certs/dbs:ca" )) # External Databases CA

  blacksmith:
    cloud_config: {} # TODO: OCFP Reference Arch based Cloud Config

    scheme: https # TODO: double check this
    domain: (( vault meta.ocfp.vault.tf "/lbs/blacksmith:domain" ))
    ip:     (( vault meta.ocfp.vault.tf "/bosh/.../0/ips/reserved:blacksmith_ip" ))
    port:   (( grab params.blacksmith_port || 3000 ))

    azs: # TODO: Check what these are - if it's for services we need 2-3 if for blacksmith it's 1, also... shouldn't CC do this?
      - (( vault meta.ocfp.vault.tf "bosh/iaas/subnets/0:availability_zone" )) # TODO: double check contract

    host: (( grab params.fqdn || params.ip ))

