#!/bin/bash
set -eu

header() {
	echo
	echo "###############################################"
	echo
	echo $*
	echo
}

cleanup() {
	for deployment in "$@"; do
		echo "> deleting ${deployment}"
		$BOSH -n -d "${deployment}" delete-deployment
	done
}

header "Validating BOSH_* environment variables..."
set | grep BOSH_ || true

header "Checking previous deployments on ${BOSH_ENVIRONMENT}..."
$BOSH deployments

header "Cleaning up from any previous deployments (if necessary)..."
cleanup ci-baseline-blacksmith

header "Deploying BASELINE environment to verify functionality..."
genesis deploy -n ci-baseline
$BOSH -d ci-baseline-blacksmith instances --vitals
cleanup ci-baseline-blacksmith
