#!/bin/bash
set -eu

header() {
	echo
	echo "###############################################"
	echo
	echo $*
	echo
}

cleanup() {
	for deployment in "$@"; do
		echo "> deleting ${deployment}"
		$BOSH -n -d "${deployment}" delete-deployment

		for disk in $($BOSH disks --orphaned | grep "${deployment}" | awk '{print $1}'); do
			echo "  - removing disk $disk"
			$BOSH -n delete-disk "$disk"
		done
	done
}

header "Validating BOSH_* environment variables..."
set | grep BOSH_ || true

header "Checking previous deployments on ${BOSH_ENVIRONMENT}..."
$BOSH deployments

header "Cleaning up from any previous deployments (if necessary)..."
cleanup ci-baseline-blacksmith
safe rm -rf secret/genesis-ci/blacksmith
safe cp -rf secret/genesis-ci/static/blacksmith secret/genesis-ci/blacksmith/ci/baseline

header "Deploying BASELINE environment to verify functionality..."
cd dev
genesis compile-kit --name blacksmith -v 9.9.9 --force # make sure hooks are executable before screaming at shipit for failing.
cd ..
genesis secrets --vault da-vault add ci-baseline
genesis deploy -n ci-baseline
$BOSH -d ci-baseline-blacksmith instances --ps
cleanup ci-baseline-blacksmith
